version: '3.8'

services:
  api:
    image: golang:alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: tail -f /dev/null
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
